# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description_en',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='description_es',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
