# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description_en',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='description_es',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_en',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='title_es',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_es',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='title_en',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='title_es',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='nugget',
            name='description_en',
            field=models.TextField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='nugget',
            name='description_es',
            field=models.TextField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='nugget',
            name='title_en',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='nugget',
            name='title_es',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='text_en',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='text_es',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='title_en',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='title_es',
            field=models.CharField(max_length=160, null=True),
        ),
    ]
