# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20180216_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_es',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='book_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Book'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='book_es',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Book'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='title_en',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='title_es',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='nugget',
            name='book_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Book'),
        ),
        migrations.AddField(
            model_name='nugget',
            name='book_es',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Book'),
        ),
        migrations.AddField(
            model_name='nugget',
            name='chapter_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Chapter'),
        ),
        migrations.AddField(
            model_name='nugget',
            name='chapter_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Chapter'),
        ),
        migrations.AddField(
            model_name='nugget',
            name='description_en',
            field=models.TextField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='nugget',
            name='description_es',
            field=models.TextField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='nugget',
            name='title_en',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='nugget',
            name='title_es',
            field=models.CharField(max_length=160, null=True),
        ),
    ]
