# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20180219_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='language',
            field=models.CharField(choices=[('es', 'Spanish'), ('en', 'English')], default='en', max_length=120),
        ),
    ]
