# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20180216_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='book_en',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='book_es',
        ),
        migrations.RemoveField(
            model_name='nugget',
            name='book_en',
        ),
        migrations.RemoveField(
            model_name='nugget',
            name='book_es',
        ),
        migrations.RemoveField(
            model_name='nugget',
            name='chapter_en',
        ),
        migrations.RemoveField(
            model_name='nugget',
            name='chapter_es',
        ),
    ]
