# Generated by Django 2.0.2 on 2018-02-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20180211_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nugget',
            name='timestamp',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
