# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-16 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20180216_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='average',
            field=models.FloatField(default=5),
        ),
    ]
