# Generated by Django 2.0.2 on 2018-02-11 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20180211_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nugget',
            old_name='golden_nugget',
            new_name='title',
        ),
    ]
