# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-17 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20180217_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name_en',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name_es',
            new_name='title_es',
        ),
    ]
