# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-17 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='text_en',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='text_es',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
