# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-17 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20180217_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='timestamp',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='title_en',
            field=models.CharField(max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='title_es',
            field=models.CharField(max_length=160, null=True),
        ),
    ]
